tipoPermiso = "rolpagina"
ocultarOpciones = "True"
DATA_DIR = "C:\\FichajesData"
BACKEND_BASE_URL = "https://web-6de6iecmrkvs.up-de-fra1-k8s-1.apps.run-on-seenode.com"
SUPABASE_URL = "https://qsxftklemuciiodwfeot.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzeGZ0a2xlbXVjaWlvZHdmZW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDA5MDIsImV4cCI6MjA3MzA3NjkwMn0.isBlFJqE1OP0v7asXPVdEsT_7uxN7Sjxi11mWWK-Na0"
